include:
  - path:
    - compose/caddy.yaml
    - compose/glance.yaml
    - compose/homeassistant.yaml
    - compose/pihole.yaml
    - compose/postgresql.yaml
    - compose/qbittorrent.yaml
    - compose/vaultwarden.yaml
    - compose/immich.yaml

networks:
  appnet:
    driver: bridge
