theme:
  background-color: 220 15.8 7.5
pages:
  - name: Startpage
    width: slim
    hide-desktop-navigation: true
    center-vertically: true
    columns:
      - size: full
        widgets:
          - type: monitor
            cache: 1m
            title: Services
            sites:
              - title: home assistant
                url: https://homeassistant.home
                check-url: http://host.docker.internal:8123
                icon: sh:home-assistant
              - title: pihole
                url: https://pi-hole.home/admin
                check-url: http://pihole:80/admin
                icon: sh:pi-hole
              - title: qbittorrent
                url: https://qbittorrent.home
                check-url: http://qbittorrent:8084
                icon: sh:qbittorrent
              - title: vaultwarden
                url: https://vaultwarden.home
                check-url: http://vaultwarden:80
                icon: si:vaultwarden
              - title: immich
                url: https://immich.home
                check-url: http://immich:2283
                icon: sh:immich
              - title: syncthing
                url: https://syncthing.home
                check-url: http://host.docker.internal:8123
                icon: sh:syncthing